# Generated by Django 5.1.1 on 2025-01-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='status',
            field=models.IntegerField(choices=[(1, 'Высшее образование'), (2, 'Повышение квалификации'), (3, 'Семинар'), (4, 'Обучающий курс'), (0, 'Другое')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
