# Generated by Django 5.1.1 on 2025-01-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_education_status_alter_myuser_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='job_speciality',
            field=models.TextField(blank=True, null=True, verbose_name='Направления работы'),
        ),
    ]
