# Generated by Django 5.1.1 on 2025-01-23 10:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_job_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='job_speciality',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Направления работы'),
        ),
    ]
