# Generated by Django 5.1.1 on 2025-01-27 20:38

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('status', models.IntegerField(choices=[(0, 'Запланирована'), (1, 'Отменена'), (2, 'Назначена'), (3, 'Проведена')], default=0, verbose_name='Статус')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Психолог')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('count_clients', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Максимальное количество участников')),
                ('status', models.IntegerField(choices=[(0, 'Запланирован'), (1, 'Отменен'), (2, 'Проведен')], default=0, verbose_name='Статус')),
                ('clients', models.ManyToManyField(blank=True, related_name='client_training', to=settings.AUTH_USER_MODEL, verbose_name='Клиенты')),
                ('psychologists', models.ManyToManyField(related_name='psychologist_training', to=settings.AUTH_USER_MODEL, verbose_name='Психологи')),
            ],
            options={
                'verbose_name': 'Тренинг',
                'verbose_name_plural': 'Тренинги',
            },
        ),
    ]
