# Generated by Django 5.1.1 on 2024-11-22 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='users.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Психолог'),
        ),
        migrations.AddField(
            model_name='training',
            name='clients',
            field=models.ManyToManyField(to='users.client', verbose_name='Клиенты'),
        ),
        migrations.AddField(
            model_name='training',
            name='psychologists',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Психологи'),
        ),
        migrations.AddField(
            model_name='trainingsphoto',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings_photo', to='events.training', verbose_name='Тренинг'),
        ),
    ]
