# Generated by Django 5.1.1 on 2025-01-30 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Психолог'),
        ),
        migrations.AddField(
            model_name='training',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='client_training', to=settings.AUTH_USER_MODEL, verbose_name='Клиенты'),
        ),
        migrations.AddField(
            model_name='training',
            name='psychologists',
            field=models.ManyToManyField(related_name='psychologist_training', to=settings.AUTH_USER_MODEL, verbose_name='Психологи'),
        ),
    ]
