# Generated by Django 5.1.1 on 2025-01-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.IntegerField(choices=[(0, 'Общая оценка'), (1, 'Оценка специалиста'), (2, 'Оценка статьи'), (3, 'Оценка тренинга')], default=0, verbose_name='Категория отзыва'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, 'На модерации'), (1, 'Отклонен'), (2, 'Опубликован')], default=0, verbose_name='Статус'),
        ),
    ]
