# Generated by Django 5.1.1 on 2025-01-21 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_answer_client_answer_comment_answer_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='client',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='offer',
        ),
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_answer', to='information.answer', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='offer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_answer', to='information.answer', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='information.category', verbose_name='Категория'),
        ),
    ]
