# Generated by Django 5.1.1 on 2025-01-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_remove_answer_client_remove_answer_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='answer',
        ),
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.ManyToManyField(related_name='comment_answer', to='information.answer', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='offer',
            name='answer',
            field=models.ManyToManyField(related_name='offer_answer', to='information.answer', verbose_name='Ответ'),
        ),
    ]
