# Generated by Django 5.1.1 on 2025-01-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_remove_comment_answer_remove_offer_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.ManyToManyField(blank=True, related_name='comment_answer', to='information.answer', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='answer',
            field=models.ManyToManyField(blank=True, related_name='offer_answer', to='information.answer', verbose_name='Ответ'),
        ),
    ]
