# Generated by Django 5.1.1 on 2025-01-24 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_article_status_alter_article_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='negative_grade',
        ),
        migrations.RemoveField(
            model_name='article',
            name='positive_grade',
        ),
        migrations.AddField(
            model_name='article',
            name='negative_grade',
            field=models.ManyToManyField(blank=True, related_name='minus', to=settings.AUTH_USER_MODEL, verbose_name='Отрицательные оценки'),
        ),
        migrations.AddField(
            model_name='article',
            name='positive_grade',
            field=models.ManyToManyField(blank=True, related_name='plus', to=settings.AUTH_USER_MODEL, verbose_name='Положительные оценки'),
        ),
    ]
