# Generated by Django 5.1.1 on 2025-01-30 09:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunnyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', tinymce.models.HTMLField(verbose_name='Вопрос')),
                ('answer1', models.CharField(max_length=200, verbose_name='Ответ № 1')),
                ('answer2', models.CharField(max_length=200, verbose_name='Ответ № 2')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Мини-тест',
                'verbose_name_plural': 'Мини-тест',
            },
        ),
        migrations.CreateModel(
            name='FunnyTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_balls', models.IntegerField(verbose_name='Минимальный бал')),
                ('max_balls', models.IntegerField(verbose_name='Максимальный бал')),
                ('result', tinymce.models.HTMLField(verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Результат мини-теста',
                'verbose_name_plural': 'Результаты мини-теста',
            },
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название теста')),
                ('testing_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата тестирования')),
                ('balls', models.IntegerField(verbose_name='Набранные балы')),
                ('result', models.CharField(max_length=200, verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Тестирование пользователя',
                'verbose_name_plural': 'Тестирование пользователей',
            },
        ),
        migrations.CreateModel(
            name='WordExclusionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', tinymce.models.HTMLField(verbose_name='Вопрос')),
                ('answer1', models.CharField(max_length=200, verbose_name='Ответ № 1')),
                ('answer2', models.CharField(max_length=200, verbose_name='Ответ № 2')),
                ('answer3', models.CharField(max_length=200, verbose_name='Ответ № 3')),
                ('answer4', models.CharField(max_length=200, verbose_name='Ответ № 4')),
                ('answer5', models.CharField(max_length=200, verbose_name='Ответ № 5')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Тест "Исключение слова"',
                'verbose_name_plural': 'Тест "Исключение слова"',
            },
        ),
        migrations.CreateModel(
            name='WordExclusionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_balls', models.IntegerField(verbose_name='Минимальный бал')),
                ('max_balls', models.IntegerField(verbose_name='Максимальный бал')),
                ('result', tinymce.models.HTMLField(verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Результат теста "Исключение слова"',
                'verbose_name_plural': 'Результаты теста "Исключение слова"',
            },
        ),
    ]
