# Generated by Django 5.1.1 on 2025-01-29 11:10

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', tinymce.models.HTMLField(verbose_name='Вопрос')),
                ('answer1', models.CharField(max_length=200, verbose_name='Ответ № 1')),
                ('answer2', models.CharField(max_length=200, verbose_name='Ответ № 2')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='Правильный ответ')),
            ],
        ),
        migrations.CreateModel(
            name='FunnyTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_balls', models.IntegerField(verbose_name='Минимальный бал')),
                ('max_balls', models.IntegerField(verbose_name='Максимальный бал')),
                ('result', tinymce.models.HTMLField(verbose_name='Результат')),
            ],
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название теста')),
                ('testing_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата тестирования')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
