# Generated by Django 5.1.1 on 2025-01-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funnytest',
            options={'verbose_name': 'Вопрос теста', 'verbose_name_plural': 'Тест-шутка'},
        ),
        migrations.AlterModelOptions(
            name='funnytestresult',
            options={'verbose_name': 'Вопрос теста', 'verbose_name_plural': 'Результаты теста-шутки'},
        ),
        migrations.AlterModelOptions(
            name='testresults',
            options={'verbose_name': 'Тестирование пользователя', 'verbose_name_plural': 'Тестирование пользователей'},
        ),
        migrations.AddField(
            model_name='testresults',
            name='balls',
            field=models.IntegerField(default=1, verbose_name='Набранные балы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresults',
            name='result',
            field=models.CharField(default=1, max_length=200, verbose_name='Результат'),
            preserve_default=False,
        ),
    ]
